### ISSUE TITLE
Typo for FALDO Import

### ISSUE THREAD

**Issue by Helisquinde** [BioInterchange/Ontologies#7]
The import line for faldo should be changed from

```<owl:imports rdf:resource="http://www.biointerchange.org/faldo.owl"/>```

to 

```<owl:imports rdf:resource="http://biohackathon.org/resource/faldo.ttl"/>```

I've been trying to open the gfvo.xml file in Protege, and FALDO is always improperly imported and assigned to TEMP. Looking at the code, it is because the wrong URL was assigned for the FALDO import. The URI itself is correct though.

**Comment by indiedotkim** [comment]
@Helisquinde I assume that your name on GitHub ("Stephen ...") is your legal name? If not, please email me your legal name at kim@codamono.com, so that I can add you to the contributors in GFVO when I commit the patch for this issue. Thanks.
